### ISSUE TITLE
Using apply_to assetic configuration

### ISSUE THREAD

**Issue by christophe-conceicao** [schmittjoh/twig.js#35]
I'm trying to use 'apply_to' configuration to match .twig files when defining my resources dependencies.

With something like this:

``` yaml
assetic:
    filters:
        twig_js:
            apply_to: "\.twig$"
```

I'm getting the following error:

```
InvalidArgumentException: The file "filters/twig_js.xml" does not exist (in: /home/christophe/devs/Symfony/vendor/bundles/Symfony/Bundle/AsseticBundle/DependencyInjection/../Resources/config).
```

I'm a symfony newbie, any clues to solve this?
